[package]
name = "Rust4SenVec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-identity = "0.4"
serde = "1.0.151"
serde_json = "1.0.91"
tch = "0.10.1"
tokenizers = "0.13.2"